enum UserManageSagaTypes {
  MANAGE_GET_USERS_WITH_PAGINATION = 'MANAGE_GET_USERS_WITH_PAGINATION',
  MANAGE_GET_USER_TO_UPDATE = 'MANAGE_GET_USER_TO_UPDATE',
  MANAGE_UPDATE_USER = 'MANAGE_UPDATE_USER',
  MANAGE_CREATE_USER = 'MANAGE_CREATE_USER',
  SET_USER_ACTIVE = 'SET_USER_ACTIVE'

}

export { UserManageSagaTypes };
