enum AuthSagasTypes {
  LOGIN_USER = 'LOGIN_USER',
  REFRESH_PASSWORD = 'REFRESH_PASSWORD',
  VERIFY_PASSWORD_CHANGE = 'VERIFY_PASSWORD_CHANGE',
  REGISTER_USER = 'REGISTER_USER',
  LOGOUT_USER = 'LOGOUT_USER',
}

export { AuthSagasTypes };
