export * from './auth/registration';
export * from './auth/login';
export * from './auth/reset';
export * from './auth/verify-refresh';
export * from './main/main';
export * from './email-activation';
export * from './main/user-manage';
export * from './platform/edit';
export * from './user-profile';
